import { Command } from 'commander'

import type { AgentMode } from './utils/constants'

export type ParsedArgs = {
  initialPrompt: string | null
  agent?: string
  clearLogs: boolean
  continue: boolean
  continueId?: string | null
  cwd?: string
  initialMode?: AgentMode
  trustProjectAgents: boolean
  /**
   * Populated ONLY when the `serve` subcommand ran (undefined otherwise).
   * NOTE: wiring `openbuff serve` into cli/src/index.tsx is a FOLLOW-UP wave;
   * this wave only PARSES the subcommand.
   */
  serve?:
    | { transport: 'stdio' }
    | { transport: 'socket'; socketPath: string; token?: string }
}

export function parseCliArgs(
  argv: string[],
  options: { version: string; exitOverride?: boolean },
): ParsedArgs {
  // The tests (and cli/src/index.tsx) pass a full argv with the node+script
  // prefix, i.e. ['node', 'openbuff', ...userArgs]. Detect an explicit leading
  // `serve` token in the user args BEFORE constructing the top-level program.
  // Registering `.command('serve')` on the same program that parses prompts
  // makes commander treat the first positional prompt as an unknown command,
  // so the two paths are kept fully separate.
  const userArgs = argv.slice(2)

  if (userArgs[0] === 'serve') {
    // `openbuff serve` subcommand (P1-T2 Wave-2). This wave only PARSES it
    // into ParsedArgs.serve; wiring it into cli/src/index.tsx is a FOLLOW-UP
    // wave.
    const serveProgram = new Command()
    serveProgram
      .name('openbuff serve')
      .description(
        'Run the ACP bridge over stdio (default) or a unix domain socket',
      )
      .option('--stdio', 'Serve the ACP bridge over stdio (default)')
      .option(
        '--socket <path>',
        'Serve the ACP bridge over a unix domain socket at the given path',
      )
      .option(
        '--socket-token <token>',
        'Token clients must present on --socket (generated by the CLI if omitted)',
      )
      .allowExcessArguments(true)
    if (options.exitOverride) {
      serveProgram.exitOverride()
    }
    // Re-attach the node/script prefix and drop the leading `serve` token so
    // commander parses only the serve-specific options.
    serveProgram.parse([argv[0], argv[1], ...userArgs.slice(1)])
    const serveOpts = serveProgram.opts()
    const serve: ParsedArgs['serve'] =
      typeof serveOpts.socket === 'string'
        ? {
            transport: 'socket',
            socketPath: serveOpts.socket,
            ...(typeof serveOpts.socketToken === 'string'
              ? { token: serveOpts.socketToken }
              : {}),
          }
        : { transport: 'stdio' }
    return {
      initialPrompt: null,
      clearLogs: false,
      continue: false,
      continueId: null,
      trustProjectAgents: false,
      serve,
    }
  }

  const program = new Command()
  program
    .name('openbuff')
    .description('Local/BYOK AI coding assistant')
    .version(options.version, '-v, --version', 'Print the CLI version')
    .option(
      '--agent <agent-id>',
      'Run a specific agent id (skips loading local .agents overrides)',
    )
    .option('--clear-logs', 'Remove any existing CLI log files before starting')
    .option(
      '--continue [conversation-id]',
      'Continue from a previous conversation (optionally specify a conversation id)',
    )
    .option(
      '--cwd <directory>',
      'Set the working directory (default: current directory)',
    )
    .option('--plan', 'Start in PLAN mode')
    .option('--local', 'Local/BYOK mode (default; kept for compatibility)')
    .option(
      '--trust-project-agents',
      'Allow executable agents and MCP config from this project or its parent directory',
    )
    .addHelpText(
      'after',
      '\nCommands:\n  init                           Create local project context',
    )
    .helpOption('-h, --help', 'Show this help message')
    .argument('[prompt...]', 'Initial prompt to send to the agent')
    .allowExcessArguments(true)

  if (options.exitOverride) {
    program.exitOverride()
  }
  program.parse(argv)

  const parsed = program.opts()
  const continueFlag = parsed.continue
  return {
    initialPrompt: program.args.length > 0 ? program.args.join(' ') : null,
    agent: parsed.agent,
    clearLogs: parsed.clearLogs || false,
    continue: Boolean(continueFlag),
    continueId:
      typeof continueFlag === 'string' && continueFlag.trim().length > 0
        ? continueFlag.trim()
        : null,
    cwd: parsed.cwd,
    initialMode: parsed.plan ? 'PLAN' : undefined,
    trustProjectAgents: parsed.trustProjectAgents === true,
    serve: undefined,
  }
}
