import { Command } from 'commander'

import type { AgentMode } from './utils/constants'

export type ParsedArgs = {
  initialPrompt: string | null
  agent?: string
  clearLogs: boolean
  continue: boolean
  continueId?: string | null
  cwd?: string
  initialMode?: AgentMode
  trustProjectAgents: boolean
  /**
   * Populated ONLY when the `serve` subcommand ran (undefined otherwise).
   * `trustProjectAgents` mirrors the serve-level `--trust-project-agents`
   * flag (default false); cli/src/index.tsx resolves the effective serve
   * trust (flag OR trusted-roots allowlist) from it (NEW-2, design §12.8).
   */
  serve?:
    | { transport: 'stdio'; agentId?: string; trustProjectAgents: boolean }
    | {
        transport: 'socket'
        socketPath: string
        token?: string
        agentId?: string
        trustProjectAgents: boolean
      }
  /**
   * Populated ONLY when the `mcp` subcommand ran (undefined otherwise).
   * P1-T4: an MCP server over stdio exposing the SDK's read-only in-process
   * surfaces. `--mutations` arms the opt-in receipt-backed edit tooling
   * (`apply_edits`); the server stays read-only unless it is passed.
   */
  mcp?: { mutations?: boolean }
  /**
   * Populated ONLY when the `run` subcommand ran (undefined otherwise).
   * P1-T5: headless/CI mode — run the agent non-interactively on a prompt.
   * `json` selects the machine-readable ndjson event stream on stdout
   * (otherwise only `text` events stream); `agentId` overrides the default
   * 'base' agent. The process exit code reflects the run outcome.
   */
  run?: { prompt: string; json: boolean; agentId?: string }
  /**
   * Populated ONLY when the `replay` subcommand ran (undefined otherwise).
   * P2-T3: deterministic replay/fork of a P2-T2 run journal. `runId` names
   * the run to replay (required positional); `fromStep` replays from a step
   * boundary; `model` overrides the replayed run's model; `json` selects the
   * machine-readable ndjson event stream on stdout (otherwise a
   * human-readable replay trace). The process exit code reflects the replay
   * outcome.
   */
  replay?: { runId: string; fromStep?: number; model?: string; json: boolean }
  /**
   * P1-T3 TUI attach mode. Populated ONLY when `--attach` (optionally with
   * `--serve-socket`/`--serve-token`) is passed; `undefined` keeps the
   * default in-process backend. When set, the CLI's client runs prompts
   * against a live `openbuff serve` over ACP instead of in-process, and
   * supports detach/reattach to the live session.
   */
  attach?: { socketPath?: string; token?: string }
}

export function parseCliArgs(
  argv: string[],
  options: { version: string; exitOverride?: boolean },
): ParsedArgs {
  // The tests (and cli/src/index.tsx) pass a full argv with the node+script
  // prefix, i.e. ['node', 'openbuff', ...userArgs]. Detect an explicit leading
  // subcommand token (`serve`, `mcp`) in the user args BEFORE constructing the
  // top-level program.
  // Registering `.command('serve')` on the same program that parses prompts
  // makes commander treat the first positional prompt as an unknown command,
  // so the two paths are kept fully separate.
  const userArgs = argv.slice(2)

  if (userArgs[0] === 'serve') {
    // `openbuff serve` subcommand (P1-T2 Wave-2). This wave only PARSES it
    // into ParsedArgs.serve; wiring it into cli/src/index.tsx is a FOLLOW-UP
    // wave.
    const serveProgram = new Command()
    serveProgram
      .name('openbuff serve')
      .description(
        'Run the ACP bridge over stdio (default) or a unix domain socket',
      )
      .option('--stdio', 'Serve the ACP bridge over stdio (default)')
      .option(
        '--socket <path>',
        'Serve the ACP bridge over a unix domain socket at the given path',
      )
      .option(
        '--socket-token <token>',
        'Token clients must present on --socket (generated by the CLI if omitted)',
      )
      .option(
        '--agent <id>',
        'Run a specific agent id for served prompt turns (default: base)',
      )
      .option(
        '--trust-project-agents',
        'Allow executable agents and MCP config from this project or its parent directory',
      )
      .allowExcessArguments(true)
    if (options.exitOverride) {
      serveProgram.exitOverride()
    }
    // Re-attach the node/script prefix and drop the leading `serve` token so
    // commander parses only the serve-specific options.
    serveProgram.parse([argv[0], argv[1], ...userArgs.slice(1)])
    const serveOpts = serveProgram.opts()
    const serveAgentId =
      typeof serveOpts.agent === 'string' ? serveOpts.agent : undefined
    // Serve-level trust flag (NEW-2): defaults to false when absent.
    const serveTrustProjectAgents = serveOpts.trustProjectAgents === true
    // SEC-4: an explicitly EMPTY --socket-token ("" or whitespace) is an
    // auth bypass — any client satisfies an empty expected token — so it is
    // rejected, never carried. Omitting the flag stays the documented path
    // (the CLI generates a 256-bit CSPRNG token).
    if (
      typeof serveOpts.socketToken === 'string' &&
      serveOpts.socketToken.trim().length === 0
    ) {
      serveProgram.error(
        '--socket-token must not be empty (omit it to generate one)',
      )
    }
    const serve: ParsedArgs['serve'] =
      typeof serveOpts.socket === 'string'
        ? {
            transport: 'socket',
            socketPath: serveOpts.socket,
            trustProjectAgents: serveTrustProjectAgents,
            ...(typeof serveOpts.socketToken === 'string'
              ? { token: serveOpts.socketToken }
              : {}),
            ...(serveAgentId ? { agentId: serveAgentId } : {}),
          }
        : {
            transport: 'stdio',
            trustProjectAgents: serveTrustProjectAgents,
            ...(serveAgentId ? { agentId: serveAgentId } : {}),
          }
    return {
      initialPrompt: null,
      clearLogs: false,
      continue: false,
      continueId: null,
      trustProjectAgents: false,
      serve,
    }
  }

  if (userArgs[0] === 'mcp') {
    // `openbuff mcp` subcommand (P1-T4). Kept off the top-level program for
    // exactly the reason the comment above names for `serve`: registering
    // `.command('mcp')` there would break positional prompts.
    const mcpProgram = new Command()
    mcpProgram
      .name('openbuff mcp')
      .description('Run the Openbuff MCP server over stdio')
      .option(
        '--mutations',
        'Arm receipt-backed edit tooling (apply_edits) on the MCP server',
      )
      .allowExcessArguments(true)
      // Tolerate unknown options too: an MCP host config may pass flags a
      // future CLI understands; failing hard on them would break the host.
      .allowUnknownOption(true)
    if (options.exitOverride) {
      mcpProgram.exitOverride()
    }
    // Re-attach the node/script prefix and drop the leading `mcp` token so
    // commander parses only the mcp-specific options (currently --mutations).
    mcpProgram.parse([argv[0], argv[1], ...userArgs.slice(1)])
    return {
      initialPrompt: null,
      clearLogs: false,
      continue: false,
      continueId: null,
      trustProjectAgents: false,
      mcp: { mutations: mcpProgram.opts().mutations === true },
    }
  }

  if (userArgs[0] === 'run') {
    // `openbuff run` subcommand (P1-T5): headless/CI mode. Kept off the
    // top-level program for exactly the reason the comment above names for
    // `serve`: registering `.command('run')` there would break positional
    // prompts. stdout carries ONLY the machine-readable stream in --json mode.
    const runProgram = new Command()
    runProgram
      .name('openbuff run')
      .description(
        'Run an agent non-interactively on a prompt and exit (headless/CI mode)',
      )
      .option(
        '--json',
        'Emit machine-readable events (one JSON object per line) on stdout',
      )
      .option('--agent <id>', 'Run a specific agent id (default: base)')
      .argument('<prompt...>', 'Prompt to send to the agent')
      .allowExcessArguments(true)
    if (options.exitOverride) {
      runProgram.exitOverride()
    }
    // Re-attach the node/script prefix and drop the leading `run` token so
    // commander parses only the run-specific options. `.argument('<prompt...>')
    // is required, so a run with no prompt errors via commander's error path
    // (exitOverride in tests, process exit in production) and never launches.
    runProgram.parse([argv[0], argv[1], ...userArgs.slice(1)])
    const runOpts = runProgram.opts()
    const prompt = runProgram.args.join(' ')
    const runAgentId =
      typeof runOpts.agent === 'string' ? runOpts.agent : undefined
    return {
      initialPrompt: null,
      clearLogs: false,
      continue: false,
      continueId: null,
      trustProjectAgents: false,
      run: {
        prompt,
        json: runOpts.json === true,
        ...(runAgentId ? { agentId: runAgentId } : {}),
      },
    }
  }

  if (userArgs[0] === 'replay') {
    // `openbuff replay` subcommand (P2-T3): deterministic replay/fork of a
    // P2-T2 run journal. Kept off the top-level program for exactly the
    // reason the comment above names for `serve`: registering
    // `.command('replay')` there would break positional prompts. stdout
    // carries ONLY the machine-readable stream in --json mode.
    const replayProgram = new Command()
    replayProgram
      .name('openbuff replay')
      .description(
        'Replay a journaled run deterministically (optionally from a step boundary / with a model override)',
      )
      .argument('<runId>', 'Run id to replay')
      .option('--from-step <n>', 'Replay from a step boundary')
      .option('--model <id>', 'Override the model for the replayed run')
      .option(
        '--json',
        'Emit machine-readable events (one JSON object per line) on stdout',
      )
      .allowExcessArguments(true)
    if (options.exitOverride) {
      replayProgram.exitOverride()
    }
    // Re-attach the node/script prefix and drop the leading `replay` token so
    // commander parses only the replay-specific options. `.argument('<runId>')
    // is required, so a replay with no runId errors via commander's error path
    // (exitOverride in tests, process exit in production) and never runs.
    replayProgram.parse([argv[0], argv[1], ...userArgs.slice(1)])
    const replayOpts = replayProgram.opts()
    const runId = replayProgram.args[0]
    // Validate --from-step: commander passes the raw string through, so the
    // documented fail-closed contract requires a strict DECIMAL integer.
    // Plain `Number()` parsing is too lax: '' / '   ' parse to 0 (silently
    // replaying from step 0) and '0x10' / '1e2' parse as integers, so an
    // explicit decimal-digit check runs first and any other shape errors.
    let fromStep: number | undefined
    if (typeof replayOpts.fromStep === 'string') {
      const rawFromStep = replayOpts.fromStep.trim()
      if (!/^\d+$/.test(rawFromStep)) {
        replayProgram.error(
          `--from-step must be a non-negative integer, got ${JSON.stringify(replayOpts.fromStep)}`,
        )
      }
      fromStep = Number(rawFromStep)
    }
    const replayModel =
      typeof replayOpts.model === 'string' ? replayOpts.model : undefined
    return {
      initialPrompt: null,
      clearLogs: false,
      continue: false,
      continueId: null,
      trustProjectAgents: false,
      replay: {
        runId,
        ...(fromStep !== undefined ? { fromStep } : {}),
        ...(replayModel ? { model: replayModel } : {}),
        json: replayOpts.json === true,
      },
    }
  }

  const program = new Command()
  program
    .name('openbuff')
    .description('Local/BYOK AI coding assistant')
    .version(options.version, '-v, --version', 'Print the CLI version')
    .option(
      '--agent <agent-id>',
      'Run a specific agent id (skips loading local .agents overrides)',
    )
    .option('--clear-logs', 'Remove any existing CLI log files before starting')
    .option(
      '--continue [conversation-id]',
      'Continue from a previous conversation (optionally specify a conversation id)',
    )
    .option(
      '--cwd <directory>',
      'Set the working directory (default: current directory)',
    )
    .option('--plan', 'Start in PLAN mode')
    .option('--local', 'Local/BYOK mode (default; kept for compatibility)')
    .option(
      '--trust-project-agents',
      'Allow executable agents and MCP config from this project or its parent directory',
    )
    .option(
      '--attach',
      'Attach to a running `openbuff serve` over ACP instead of running in-process',
    )
    .option(
      '--serve-socket <path>',
      'Unix socket of a running `openbuff serve` (used with --attach; or OPENBUFF_SERVE_SOCKET)',
    )
    .option(
      '--serve-token <token>',
      'Auth token for --serve-socket (or OPENBUFF_SERVE_TOKEN)',
    )
    .addHelpText(
      'after',
      '\nCommands:\n  init                           Create local project context',
    )
    .helpOption('-h, --help', 'Show this help message')
    .argument('[prompt...]', 'Initial prompt to send to the agent')
    .allowExcessArguments(true)

  if (options.exitOverride) {
    program.exitOverride()
  }
  program.parse(argv)

  const parsed = program.opts()
  const continueFlag = parsed.continue
  // P1-T3: --attach is OFF by default. The parser is pure (flags only); the
  // OPENBUFF_SERVE_SOCKET/TOKEN env fallback is applied by cli/src/index.tsx.
  const attachSocketPath =
    typeof parsed.serveSocket === 'string' && parsed.serveSocket.length > 0
      ? parsed.serveSocket
      : undefined
  const attachToken =
    typeof parsed.serveToken === 'string' && parsed.serveToken.length > 0
      ? parsed.serveToken
      : undefined
  const attach =
    parsed.attach === true
      ? {
          ...(attachSocketPath ? { socketPath: attachSocketPath } : {}),
          ...(attachToken ? { token: attachToken } : {}),
        }
      : undefined
  if (parsed.attach === true && !attachSocketPath) {
    program.error(
      '--attach requires a serve socket: pass --serve-socket <path> or set OPENBUFF_SERVE_SOCKET',
    )
  }
  return {
    initialPrompt: program.args.length > 0 ? program.args.join(' ') : null,
    agent: parsed.agent,
    clearLogs: parsed.clearLogs || false,
    continue: Boolean(continueFlag),
    continueId:
      typeof continueFlag === 'string' && continueFlag.trim().length > 0
        ? continueFlag.trim()
        : null,
    cwd: parsed.cwd,
    initialMode: parsed.plan ? 'PLAN' : undefined,
    trustProjectAgents: parsed.trustProjectAgents === true,
    serve: undefined,
    mcp: undefined,
    ...(attach ? { attach } : {}),
  }
}
