import { Command } from 'commander'

import type { AgentMode } from './utils/constants'

export type ParsedArgs = {
  initialPrompt: string | null
  agent?: string
  clearLogs: boolean
  continue: boolean
  continueId?: string | null
  cwd?: string
  initialMode?: AgentMode
  trustProjectAgents: boolean
  /**
   * Populated ONLY when the `serve` subcommand ran (undefined otherwise).
   * `trustProjectAgents` mirrors the serve-level `--trust-project-agents`
   * flag (default false); cli/src/index.tsx resolves the effective serve
   * trust (flag OR trusted-roots allowlist) from it (NEW-2, design §12.8).
   */
  serve?:
    | { transport: 'stdio'; agentId?: string; trustProjectAgents: boolean }
    | {
        transport: 'socket'
        socketPath: string
        token?: string
        agentId?: string
        trustProjectAgents: boolean
      }
  /**
   * Populated ONLY when the `mcp` subcommand ran (undefined otherwise).
   * P1-T4: an MCP server over stdio exposing the SDK's read-only in-process
   * surfaces; receipt-backed edits and memory search stay opt-in/OFF (see
   * sdk/src/mcp/server.ts), so there are no mcp-level flags this wave.
   */
  mcp?: Record<string, never>
}

export function parseCliArgs(
  argv: string[],
  options: { version: string; exitOverride?: boolean },
): ParsedArgs {
  // The tests (and cli/src/index.tsx) pass a full argv with the node+script
  // prefix, i.e. ['node', 'openbuff', ...userArgs]. Detect an explicit leading
  // subcommand token (`serve`, `mcp`) in the user args BEFORE constructing the
  // top-level program.
  // Registering `.command('serve')` on the same program that parses prompts
  // makes commander treat the first positional prompt as an unknown command,
  // so the two paths are kept fully separate.
  const userArgs = argv.slice(2)

  if (userArgs[0] === 'serve') {
    // `openbuff serve` subcommand (P1-T2 Wave-2). This wave only PARSES it
    // into ParsedArgs.serve; wiring it into cli/src/index.tsx is a FOLLOW-UP
    // wave.
    const serveProgram = new Command()
    serveProgram
      .name('openbuff serve')
      .description(
        'Run the ACP bridge over stdio (default) or a unix domain socket',
      )
      .option('--stdio', 'Serve the ACP bridge over stdio (default)')
      .option(
        '--socket <path>',
        'Serve the ACP bridge over a unix domain socket at the given path',
      )
      .option(
        '--socket-token <token>',
        'Token clients must present on --socket (generated by the CLI if omitted)',
      )
      .option(
        '--agent <id>',
        'Run a specific agent id for served prompt turns (default: base)',
      )
      .option(
        '--trust-project-agents',
        'Allow executable agents and MCP config from this project or its parent directory',
      )
      .allowExcessArguments(true)
    if (options.exitOverride) {
      serveProgram.exitOverride()
    }
    // Re-attach the node/script prefix and drop the leading `serve` token so
    // commander parses only the serve-specific options.
    serveProgram.parse([argv[0], argv[1], ...userArgs.slice(1)])
    const serveOpts = serveProgram.opts()
    const serveAgentId =
      typeof serveOpts.agent === 'string' ? serveOpts.agent : undefined
    // Serve-level trust flag (NEW-2): defaults to false when absent.
    const serveTrustProjectAgents = serveOpts.trustProjectAgents === true
    // SEC-4: an explicitly EMPTY --socket-token ("" or whitespace) is an
    // auth bypass — any client satisfies an empty expected token — so it is
    // rejected, never carried. Omitting the flag stays the documented path
    // (the CLI generates a 256-bit CSPRNG token).
    if (
      typeof serveOpts.socketToken === 'string' &&
      serveOpts.socketToken.trim().length === 0
    ) {
      serveProgram.error(
        '--socket-token must not be empty (omit it to generate one)',
      )
    }
    const serve: ParsedArgs['serve'] =
      typeof serveOpts.socket === 'string'
        ? {
            transport: 'socket',
            socketPath: serveOpts.socket,
            trustProjectAgents: serveTrustProjectAgents,
            ...(typeof serveOpts.socketToken === 'string'
              ? { token: serveOpts.socketToken }
              : {}),
            ...(serveAgentId ? { agentId: serveAgentId } : {}),
          }
        : {
            transport: 'stdio',
            trustProjectAgents: serveTrustProjectAgents,
            ...(serveAgentId ? { agentId: serveAgentId } : {}),
          }
    return {
      initialPrompt: null,
      clearLogs: false,
      continue: false,
      continueId: null,
      trustProjectAgents: false,
      serve,
    }
  }

  if (userArgs[0] === 'mcp') {
    // `openbuff mcp` subcommand (P1-T4). Kept off the top-level program for
    // exactly the reason the comment above names for `serve`: registering
    // `.command('mcp')` there would break positional prompts.
    const mcpProgram = new Command()
    mcpProgram
      .name('openbuff mcp')
      .description('Run the Openbuff MCP server over stdio')
      .allowExcessArguments(true)
      // Tolerate unknown options too: an MCP host config may pass flags a
      // future CLI understands; failing hard on them would break the host.
      .allowUnknownOption(true)
    if (options.exitOverride) {
      mcpProgram.exitOverride()
    }
    // Re-attach the node/script prefix and drop the leading `mcp` token so
    // commander parses only the mcp-specific options (none yet).
    mcpProgram.parse([argv[0], argv[1], ...userArgs.slice(1)])
    return {
      initialPrompt: null,
      clearLogs: false,
      continue: false,
      continueId: null,
      trustProjectAgents: false,
      mcp: {},
    }
  }

  const program = new Command()
  program
    .name('openbuff')
    .description('Local/BYOK AI coding assistant')
    .version(options.version, '-v, --version', 'Print the CLI version')
    .option(
      '--agent <agent-id>',
      'Run a specific agent id (skips loading local .agents overrides)',
    )
    .option('--clear-logs', 'Remove any existing CLI log files before starting')
    .option(
      '--continue [conversation-id]',
      'Continue from a previous conversation (optionally specify a conversation id)',
    )
    .option(
      '--cwd <directory>',
      'Set the working directory (default: current directory)',
    )
    .option('--plan', 'Start in PLAN mode')
    .option('--local', 'Local/BYOK mode (default; kept for compatibility)')
    .option(
      '--trust-project-agents',
      'Allow executable agents and MCP config from this project or its parent directory',
    )
    .addHelpText(
      'after',
      '\nCommands:\n  init                           Create local project context',
    )
    .helpOption('-h, --help', 'Show this help message')
    .argument('[prompt...]', 'Initial prompt to send to the agent')
    .allowExcessArguments(true)

  if (options.exitOverride) {
    program.exitOverride()
  }
  program.parse(argv)

  const parsed = program.opts()
  const continueFlag = parsed.continue
  return {
    initialPrompt: program.args.length > 0 ? program.args.join(' ') : null,
    agent: parsed.agent,
    clearLogs: parsed.clearLogs || false,
    continue: Boolean(continueFlag),
    continueId:
      typeof continueFlag === 'string' && continueFlag.trim().length > 0
        ? continueFlag.trim()
        : null,
    cwd: parsed.cwd,
    initialMode: parsed.plan ? 'PLAN' : undefined,
    trustProjectAgents: parsed.trustProjectAgents === true,
    serve: undefined,
    mcp: undefined,
  }
}
